[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1e1e2e"

[colors.cursor]
cursor = "#d8dee9"



[window]
padding.x = 5
padding.y = 2
decorations = "Full"
opacity = 0.75
#blur = true
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold" }

[cursor]
style = { shape = "Block", blinking = "Off" }



