[general]
import = [
    "~/.config/alacritty/nord.toml",
]

[env]
TERM = "xterm-256color"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true




[window]
padding.x = 5
padding.y = 2
decorations = "Full"
#opacity = 0.75
blur = true
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
size = 14
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold" }

[cursor]
style = { shape = "Block", blinking = "On" }



