# Colors (Nordic)

[colors.primary]
background = '#242933'
foreground = '#BBC3D4'
dim_foreground = '#a5abb6'

[colors.cursor]
text = '#242933'
cursor = '#d8dee9'

[colors.vi_mode_cursor]
text = '#242933'
cursor = '#d8dee9'

[colors.normal]
black = '#3B4252'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = CellForeground
background = '#4c566a'
