# Colors (Nordic)

[colors.primary]
background = '#242933'
foreground = '#BBC3D4'
dim_foreground = '#a5abb6'

[colors.cursor]
text = '#242933'
cursor = '#d8dee9'

[colors.vi_mode_cursor]
text = '#242933'
cursor = '#d8dee9'

[colors.normal]
black = '#242933'
#black = '#2E3440'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#8FBCBB'
white = '#BDC5BD'

[colors.bright]
black = '#4C566A'
red = '#C5727A'
green = '#B1C89D'
yellow = '#EFD49F'
blue = '#81A1C1'
magenta = '#BE9DB8'
cyan = '#9FC6C5'
white = '#eceff4'

[colors.selection]
text = '#242933'
background = '#4c566a'
